### ISSUE TITLE
Some Text can't be decode, and also undefinedr

### ISSUE THREAD

**Issue by KingPanda-Development** [GuckTubeYT/GrowTools#2]
Hello GuckTubeYT, can you check this issue? in the new Item.dat of Growtopia v4.44?
**Thank you if you can fix this issue** 🙏

![image](https://github.com/GuckTubeYT/GrowTools/assets/72608447/1480cc6e-9acf-4b42-bcf7-26ca38534553)
![image](https://github.com/GuckTubeYT/GrowTools/assets/72608447/1459ff06-3885-4b53-a1b0-20c5b3740ea5)

**Comment by GuckTubeYT** [comment]
fixed, thanks for reporting the issue
