### ISSUE TITLE
Bug Processing...  not finished

### ISSUE THREAD

**Issue by SiDeoGTPS** [GuckTubeYT/GrowTools#8]

**Comment by JadlionHD** [comment]
Can you tell more detail information regarding your issue?

**Comment by SiDeoGTPS** [comment]
> Can you tell more detail bug information regarding your issue?

me use /itocdata bug processing not finish2 bro

**Comment by JadlionHD** [comment]
> me use /itocdata bug processing not finish2 bro
If you mean the telegram bot command, then this repo are not related with that.
Consider use their "/report" command instead

**Comment by GuckTubeYT** [comment]
> > Can you tell more detail bug information regarding your issue?
> 
> me use /itocdata bug processing not finish2 bro

i am stop updating GBot now, sorry 🙏🏽
